# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0/system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_ps7_0_axi_periph_0/system_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_ps7_0_axi_periph_0 || ORIG_REF_NAME==system_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_5/system_axi_gpio_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_5 || ORIG_REF_NAME==system_axi_gpio_0_5} -quiet] -quiet

# IP: bd/system/ip/system_axi_gpio_0_6/system_axi_gpio_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_6 || ORIG_REF_NAME==system_axi_gpio_0_6} -quiet] -quiet

# XDC: /home/ypwang/project_code/Xilinx_Summer_School/summter_lab/lab2/lab2.gen/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_processing_system7_0_0 || ORIG_REF_NAME==system_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/ypwang/project_code/Xilinx_Summer_School/summter_lab/lab2/lab2.gen/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ypwang/project_code/Xilinx_Summer_School/summter_lab/lab2/lab2.gen/sources_1/bd/system/ip/system_rst_ps7_0_100M_0/system_rst_ps7_0_100M_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_rst_ps7_0_100M_0 || ORIG_REF_NAME==system_rst_ps7_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ypwang/project_code/Xilinx_Summer_School/summter_lab/lab2/lab2.gen/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc

# XDC: /home/ypwang/project_code/Xilinx_Summer_School/summter_lab/lab2/lab2.gen/sources_1/bd/system/ip/system_axi_gpio_0_5/system_axi_gpio_0_5_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_5 || ORIG_REF_NAME==system_axi_gpio_0_5} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ypwang/project_code/Xilinx_Summer_School/summter_lab/lab2/lab2.gen/sources_1/bd/system/ip/system_axi_gpio_0_5/system_axi_gpio_0_5_ooc.xdc

# XDC: /home/ypwang/project_code/Xilinx_Summer_School/summter_lab/lab2/lab2.gen/sources_1/bd/system/ip/system_axi_gpio_0_5/system_axi_gpio_0_5.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_5 || ORIG_REF_NAME==system_axi_gpio_0_5} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ypwang/project_code/Xilinx_Summer_School/summter_lab/lab2/lab2.gen/sources_1/bd/system/ip/system_axi_gpio_0_6/system_axi_gpio_0_6_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_6 || ORIG_REF_NAME==system_axi_gpio_0_6} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ypwang/project_code/Xilinx_Summer_School/summter_lab/lab2/lab2.gen/sources_1/bd/system/ip/system_axi_gpio_0_6/system_axi_gpio_0_6_ooc.xdc

# XDC: /home/ypwang/project_code/Xilinx_Summer_School/summter_lab/lab2/lab2.gen/sources_1/bd/system/ip/system_axi_gpio_0_6/system_axi_gpio_0_6.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_gpio_0_6 || ORIG_REF_NAME==system_axi_gpio_0_6} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/ypwang/project_code/Xilinx_Summer_School/summter_lab/lab2/lab2.gen/sources_1/bd/system/system_ooc.xdc
